# git tag x.x.x.x
# git push gh --tags

name: .NET WPF Continuous Deployment

on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        channel: [Dev, Prod_Sideload, Prod_Store]
        targetPlatform: [x86, x64]
        include:
          - channel: Dev
            ChannelName: Dev
            Configuration: Debug
            DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-dev
            MsixPackageId: RichillCapital.TraderStudio.Desktop.Dev
            MsixPublisherId: CN=RichillCapital
            MsixPackageDisplayName: RichillCapital TraderStudio (Dev)

          - channel: Prod_Sideload
            Configuration: Release
            ChannelName: Prod_Sideload
            DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-prod
            MsixPackageId: RichillCapital.TraderStudio.Desktop.ProdSideload
            MsixPublisherId: CN=RichillCapital
            MsixPackageDisplayName: RichillCapital TraderStudio (ProdSideload)

          - channel: Prod_Store
            Configuration: Release
            ChannelName: Prod_Store
            DistributionUrl:
            MsixPackageId: RichillCapital.TraderStudio.Desktop.ProdStore
            MsixPublisherId: CN=RichillCapital
            MsixPackageDisplayName: RichillCapital TraderStudio (ProdStore)

    runs-on: windows-latest

    env:
      Wap_Project_Directory: ./Packaging/RichillCapital.TraderStudio.Desktop.Package
      Wap_Project_Path: ./Packaging/RichillCapital.TraderStudio.Desktop.Package/RichillCapital.TraderStudio.Desktop.Package.wapproj


      App_Packages_Archive: AppPackages.zip
      App_Packages_Directory: AppPackages
      Solution_Path: ./RichillCapital.TraderStudio.Desktop.sln
      
      Certificate_Name: RichillCapital.TraderStudio.Desktop.pfx
      Wpf_Project_Path: ./RichillCapital.TraderStudio.Desktop.csproj


    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Use Nerdbank.GitVersioning 
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    - name: Update Version
      run: |
        [xml]$manifest = Get-Content "./$env:Wap_Project_Directory/Package.appxmanifest"
        $manifest.Package.Identity.Version = "${{ steps.nbgv.outputs.SimpleVersion }}.0"
        $manifest.save("./$env:Wap_Project_Directory/Package.appxmanifest")
    
    - name: Build and Tests with Cake Tool
      uses: cake-build/cake-action@v2
      with:
        script-path: build.cake
        target: default
        verbosity: Diagnostic
        
    - name: Decode Signing Certificate
      run: |
        $certificateContent = [System.Convert]::FromBase64String("${{ secrets.BASE64_CERTIFICATE }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath $env:Certificate_Name
        [IO.File]::WriteAllBytes("$certificatePath", $certificateContent)
      if: matrix.ChannelName != 'Prod_Store'

    - name: Publish Application Package for ${{ matrix.ChannelName }}
      run: msbuild $env:Wap_Project_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:Certificate_Name /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      if: matrix.ChannelName != 'Prod_Store'
      env:
        AppxBundle: Never
        AppInstallerUri: ${{ matrix.DistributionUrl }}
        BuildMode: SideloadOnly
        Configuration: ${{ matrix.Configuration }}
        GenerateAppInstallerFile: True
        TargetPlatform: ${{ matrix.targetplatform }}

    - name: Publish Application Package for ${{ matrix.ChannelName }}
      run: msbuild $env:Wap_Project_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:GenerateAppInstallerFile=$env:GenerateAppInstallerFile /p:AppxPackageSigningEnabled=$env:AppxPackageSigningEnabled
      if: matrix.ChannelName == 'Prod_Store'
      env:
        AppxBundle: Never
        AppxPackageSigningEnabled: False
        BuildMode: StoreUpload
        Configuration: ${{ matrix.Configuration }}
        GenerateAppInstallerFile: False
        TargetPlatform: ${{ matrix.targetplatform }}

    - name: Remove Signing Certificate
      run: Remove-Item -Path $env:Wap_Project_Directory/$env:Certificate_Name

    - name: Create Archive
      run: Compress-Archive -Path $env:Wap_Project_Directory\$env:App_Packages_Directory\* -DestinationPath $env:Wap_Project_Directory\$env:App_Packages_Directory\$env:App_Packages_Archive

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref}}.${{matrix.ChannelName}}.${{ matrix.targetplatform }}
        release_name:  ${{ github.ref }}.${{ matrix.ChannelName }}.${{ matrix.targetplatform }}
        draft: false
        prerelease: false

    - name: Update Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.Wap_Project_Directory }}\${{ env.App_Packages_Directory }}\${{ env.App_Packages_Archive }}
        asset_name: ${{ env.App_Packages_Archive }}
        asset_content_type: application/zip