name:  Wpf Continuous Delivery

on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        channel: [Dev, Prod_Sideload, Prod_Store]
        targetPlatform: [x86, x64]
        include:
          - channel: Dev
            ChannelName: Dev
            Configuration: Debug
            DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-dev
            MsixPackageId: MyWPFApp.DevOpsDemo.Dev
            MsixPublisherId: CN=GitHubActionsDemo
            MsixPackageDisplayName: MyWPFApp (Dev)

          - channel: Prod_Sideload
            Configuration: Release
            ChannelName: Prod_Sideload
            DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-prod
            MsixPackageId: MyWPFApp.DevOpsDemo.ProdSideload
            MsixPublisherId: CN=GitHubActionsDemo
            MsixPackageDisplayName: MyWPFApp (ProdSideload)

          - channel: Prod_Store
            Configuration: Release
            ChannelName: Prod_Store
            DistributionUrl:
            MsixPackageId: MyWPFApp.DevOpsDemo.ProdStore
            MsixPublisherId: CN=GitHubActionsDemo
            MsixPackageDisplayName: MyWPFApp (ProdStore)

    runs-on: windows-latest

    env:
      App_Packages_Archive: AppPackages.zip
      App_Packages_Directory: AppPackages
      SigningCertificate: RichillCapital.TraderStudio.Desktop.pfx
      Solution_Path: ./RichillCapital.TraderStudio.Desktop.sln
      
      Wpf_Project_Path: ./RichillCapital.TraderStudio.Desktop.csproj

      Wap_Project_Directory: ./Packaging/RichillCapital.TraderStudio.Desktop.Package
      Wap_Project_Name: ./Packaging/RichillCapital.TraderStudio.Desktop.Package/RichillCapital.TraderStudio.Desktop.Package.wapproj

      Actions_Allow_Unsecure_Commands: true 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Use Nerdbank.GitVersioning 
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build and Tests with Cake Tool
      uses: cake-build/cake-action@v2
      with:
        script-path: build.cake
        target: default
        verbosity: Diagnostic
        
    - name: Decode Signing Certificate
      run: |
        $certificateContent = [System.Convert]::FromBase64String("${{ secrets.BASE64_CERTIFICATE }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath $env:Certificate_Name
        [IO.File]::WriteAllBytes("$certificatePath", $certificateContent)
      if: matrix.ChannelName != 'Prod_Store'

    # # Build the Windows Application Packaging project for Dev and Prod_Sideload
    # - name: Build the Windows Application Packaging Project (wapproj) for ${{ matrix.ChannelName }}
    #   run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
    #   if: matrix.ChannelName != 'Prod_Store'
    #   env:
    #     AppxBundle: Never
    #     AppInstallerUri: ${{ matrix.DistributionUrl }}
    #     BuildMode: SideloadOnly
    #     Configuration: ${{ matrix.Configuration }}
    #     GenerateAppInstallerFile: True
    #     TargetPlatform: ${{ matrix.targetplatform }}

    # # Build the Windows Application Packaging project for Prod_Store
    # - name: Build the Windows Application Packaging Project (wapproj) for ${{ matrix.ChannelName }}
    #   run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:GenerateAppInstallerFile=$env:GenerateAppInstallerFile /p:AppxPackageSigningEnabled=$env:AppxPackageSigningEnabled
    #   if: matrix.ChannelName == 'Prod_Store'
    #   env:
    #     AppxBundle: Never
    #     AppxPackageSigningEnabled: False
    #     BuildMode: StoreUpload
    #     Configuration: ${{ matrix.Configuration }}
    #     GenerateAppInstallerFile: False
    #     TargetPlatform: ${{ matrix.targetplatform }}

    - name: Remove Signing Certificate
      run: Remove-Item -Path $env:Wap_Project_Directory/$env:Certificate_Name

    # # Archive the package
    # - name: Create archive
    #   run: Compress-Archive -Path $env:Wap_Project_Directory\$env:App_Packages_Directory\* -DestinationPath $env:Wap_Project_Directory\$env:App_Packages_Directory\$env:App_Packages_Archive

    # Create the release:  https://github.com/actions/create-release
    # - name: Create release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ github.ref}}.${{matrix.ChannelName}}.${{ matrix.targetplatform }}
    #     release_name:  ${{ github.ref }}.${{ matrix.ChannelName }}.${{ matrix.targetplatform }}
    #     draft: false
    #     prerelease: false

    # Upload release asset:   https://github.com/actions/upload-release-asset
    # - name: Update release asset
    #   id: upload-release-asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
    #     asset_path: ${{ env.Wap_Project_Directory }}\${{ env.App_Packages_Directory }}\${{ env.App_Packages_Archive }}
    #     asset_name: ${{ env.App_Packages_Archive }}
    #     asset_content_type: application/zip