name: .NET WPF Continuous Integration

on:
  push:
    branches: [ "master" ]
  
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        targetPlatform: [x86, x64]
    
    runs-on: windows-latest
    
    env:
      Solution_Name: ./RichillCapital.TraderStudio.Desktop.sln
      App_Packages_Directory: ./Packaging/RichillCapital.TraderStudio.Desktop.Package/AppPackages
      Certificate_Name: RichillCapital.TraderStudio.Desktop.pfx

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Nerdbank.GitVersioning 
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build and Tests with Cake Tool
      uses: cake-build/cake-action@v2
      with:
        script-path: build.cake
        target: default
        verbosity: Diagnostic

    - name: Decode Certificate
      run: |
        $certificateContent = [System.Convert]::FromBase64String("${{ secrets.BASE64_CERTIFICATE }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath Certs -AdditionalChildPath $Certificate_Name
        $directory = [System.IO.Path]::GetDirectoryName($certificatePath)
        if (-not (Test-Path -Path $directory)) {
            New-Item -ItemType Directory -Path $directory -Force
        }
        [IO.File]::WriteAllBytes($certificatePath, $certificateContent)
      shell: pwsh

    - name: Publish Artifact
      run: msbuild $env:Solution_Name /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=./Certs/$env:Certificate_Name /p:PackageCertificatePassword=${{ secrets.CERTIFICATE_PASSWORD}}
      env:
        AppxBundle: Never
        BuildMode: SideloadOnly
        Configuration: Release
        TargetPlatform: ${{ matrix.targetPlatform }}

    - name: Remove Certificate
      run: Remove-Item -Path ./Certs/$env:Certificate_Name
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trader-studio-desktop-${{ matrix.targetPlatform }}
        path: ${{ env.App_Packages_Directory}}