name: .NET WPF Continuous Integration

on:
  push:
    branches: [ "master" ]
  
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    
    runs-on: windows-latest
    
    env:
      DotNet_Version: 8.0.x
      Solution_Path: ./RichillCapital.TraderStudio.Desktop.sln
      Wap_Project_Directory: ./Packaging/RichillCapital.TraderStudio.Desktop.Package
      Wap_Project_Path: ./Packaging/RichillCapital.TraderStudio.Desktop.Package/RichillCapital.TraderStudio.Desktop.Package.wapproj.
      WPF_Project_Path: ./RichillCapital.TraderStudio.Desktop.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Workload
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DotNet_Version }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    
    # Decode certificate
    - name: Restore Depdenencies
      run: dotnet restore $env:Solution_Path

    - name: Build WPF Application Project
      run: dotnet build $env:WPF_Project_Path -c Release --no-restore
    
    - name: Build Windows Application Packaging Project
      run: msbuild $env:Solution_File /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle
      env:
        AppxBundle: Never
        BuildMode: SideloadOnly
        Configuration: Release
        TargetPlatform: ${{ matrix.targetplatform }}
        
    # Remove certificate
    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
        